site_name: GMU CS Virtual Open House 2021
site_author: GMU CS Dept.
copyright: '©2021 GMU CS Dept.'

nav:
  - Home: index.md
  - Schedule: schedule.md
  - Faculty Meetings: faculty-meetings.md
  - Virtual Campus Visit: virtual-visit.md
  - Resources: resources.md


theme:
  name: 'material'
  logo: 'images/GMU-Logo.png'
  favicon: 'images/GMU-Logo.png'
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: 'green'
    accent: 'light green'
    #toggle:
    #    icon: material/toggle-switch-off-outline
    #    name: Switch to dark mode

    # Toggle Light Mode
  #- scheme: gmu
  #  toggle:
  #      icon: material/toggle-switch
  #      name: Switch to light mode

plugins:
    - encryptcontent:
        title_prefix: '[Protected]'
        summary: 'This Content is Password Protected'
        placeholder: 'Click here to type the Password, then press Enter'
        decryption_failure_message: 'Invalid Password'
        encryption_info_message: 'This course content is password protected. Please enter the password.'


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      toc_depth: 3
  - attr_list
  - meta

extra:
  generator: false